/** Shared token icon map used across MarketTicker, PairSelector, and MarketsPage */
export const TOKEN_ICONS: Record<string, string> = {
  BTC:    "https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png",
  ETH:    "https://assets.coingecko.com/coins/images/279/thumb/ethereum.png",
  BNB:    "https://assets.coingecko.com/coins/images/825/thumb/bnb-icon2_2x.png",
  SOL:    "https://assets.coingecko.com/coins/images/4128/thumb/solana.png",
  XRP:    "https://assets.coingecko.com/coins/images/44/thumb/xrp-symbol-white-128.png",
  AVAX:   "https://assets.coingecko.com/coins/images/12559/thumb/Avalanche_Circle_RedWhite_Trans.png",
  DOGE:   "https://assets.coingecko.com/coins/images/5/thumb/dogecoin.png",
  ADA:    "https://assets.coingecko.com/coins/images/975/thumb/cardano.png",
  LINK:   "https://assets.coingecko.com/coins/images/877/thumb/chainlink-new-logo.png",
  DOT:    "https://assets.coingecko.com/coins/images/12171/thumb/polkadot.png",
  MATIC:  "https://assets.coingecko.com/coins/images/4713/thumb/matic-token-icon.png",
  UNI:    "https://assets.coingecko.com/coins/images/12504/thumb/uniswap-uni.png",
  ATOM:   "https://assets.coingecko.com/coins/images/1481/thumb/cosmos_hub.png",
  NEAR:   "https://assets.coingecko.com/coins/images/10365/thumb/near.jpg",
  ARB:    "https://assets.coingecko.com/coins/images/16547/thumb/photo_2023-03-29_21.47.00.jpeg",
  OP:     "https://assets.coingecko.com/coins/images/25244/thumb/Optimism.png",
  APT:    "https://assets.coingecko.com/coins/images/26455/thumb/aptos_round.png",
  LTC:    "https://assets.coingecko.com/coins/images/2/thumb/litecoin.png",
  INJ:    "https://assets.coingecko.com/coins/images/12882/thumb/Secondary_Symbol.png",
  SUI:    "https://assets.coingecko.com/coins/images/26375/thumb/sui_asset.jpeg",
  TIA:    "https://assets.coingecko.com/coins/images/31967/thumb/tia.jpg",
  SEI:    "https://assets.coingecko.com/coins/images/28205/thumb/Sei_Logo_-_Transparent.png",
  WLD:    "https://assets.coingecko.com/coins/images/31069/thumb/worldcoin.jpeg",
  JUP:    "https://assets.coingecko.com/coins/images/34188/thumb/jup.png",
  PEPE:   "https://assets.coingecko.com/coins/images/29850/thumb/pepe-token.jpeg",
  SHIB:   "https://assets.coingecko.com/coins/images/11939/thumb/shiba.png",
  FLOKI:  "https://assets.coingecko.com/coins/images/16746/thumb/PNG_image.png",
  FET:    "https://assets.coingecko.com/coins/images/5681/thumb/Fetch.jpg",
  RENDER: "https://assets.coingecko.com/coins/images/11636/thumb/rndr.png",
  GRT:    "https://assets.coingecko.com/coins/images/13397/thumb/Graph_Token.png",
  LDO:    "https://assets.coingecko.com/coins/images/13573/thumb/Lido_DAO.png",
  CRV:    "https://assets.coingecko.com/coins/images/12124/thumb/Curve.png",
  AAVE:   "https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png",
  MKR:    "https://assets.coingecko.com/coins/images/1364/thumb/Mark_Maker.png",
  SNX:    "https://assets.coingecko.com/coins/images/3406/thumb/SNX.png",
};
